server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      uri: http://localhost:8084
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/*
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        #          filters:
        #            - RewritePath=/user/(?<segment>.*), /users/$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
